name:                doom-but-in-haskell
version:             0.1.0.0
github:              "githubuser/doom-but-in-haskell"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/doom-but-in-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- OpenGL >= 3.0 && < 3.1
- linear > 1.20
- GLFW-b >= 3.3.0.0 && <= 3.3.9.0
- stm >= 2.5.1.0 && < 2.6
- mtl >= 2.3.1 && < 2.4
- directory >= 1.3 && < 1.4
- containers > 0.6 && < 0.7
- bytestring > 0.11 && < 0.12

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  doom-but-in-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doom-but-in-haskell

tests:
  doom-but-in-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doom-but-in-haskell
